//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisasterProject
{
    public partial class AddPatient
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox txtPatientName;
        protected global::System.Web.UI.WebControls.TextBox txtAge;
        protected global::System.Web.UI.WebControls.DropDownList ddlHospital;
        protected global::System.Web.UI.WebControls.DropDownList ddlIncident;
        protected global::System.Web.UI.WebControls.DropDownList ddlCaseType;
        protected global::System.Web.UI.WebControls.Button btnSubmit;
        protected global::System.Web.UI.WebControls.Button btnCancel;
    }
}